/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ian' at '2017/1/26 下午 12:32' with Gradle 3.2.1
 *
 * @author ian, @date 2017/1/26 下午 12:32
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
